name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: test (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package (editable) + test deps
        run: |
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest

  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install security tools
        run: pip install bandit==1.7.9 pip-audit==2.7.3
      - name: Bandit (scan package only, skip tests)
        run: bandit -r nba_draft_utils -x tests -q || true
      - name: pip-audit (report only; do not fail CI)
        run: pip-audit || true

